[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "denoiser"
version = "0.1.0.dev0"
description = "Discriminator for model-docking"
readme = "README.md"
requires-python = ">=3.8"

[tools.setuptools.packages.find]
where = ["src"]
