import argparse


def set_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input_features")
    parser.add_argument("--AF", help="Path for pLDDT", default=None)
    parser.add_argument("--energy", default=None)
    parser.add_argument("--self-docking", action="store_true")
    parser.add_argument("--no-gald", action="store_true")

    # Local model
    parser.add_argument("--lr", default=6 * 1.0e-4)
    parser.add_argument("--l0_in_features", default=1 + 20 + 20 + 1 + 1)
    parser.add_argument("--num_layers", default=(4, 6, 3))
    parser.add_argument("--inter_hidden_channels", default=(16, 16))
    parser.add_argument("--data_suffix", default=".auxil")
    parser.add_argument("--drop_out", default=0.3)
    parser.add_argument("--use_l1_feature", default=False)
    parser.add_argument("--w_lossG", default=5.0)
    parser.add_argument("--w_lossL", default=0.5)
    parser.add_argument("--w_lossR", default=0.3)
    parser.add_argument("--w_lossHbond", default=1.0)
    parser.add_argument("--w_lossPolApol", default=3.8)
    parser.add_argument("--w_lossApolApol", default=0.8)
    parser.add_argument("--w_lossDist", default=0.05)
    parser.add_argument("--w_reg", default=5.0e-5)
    parser.add_argument("--masking_coeff", default=0)
    parser.add_argument("--fix_random_seed", default=True)
    parser.add_argument("--distance_map_dist", default=5)
    parser.add_argument("--threshold_distance_diff", default=5)
    parser.add_argument("--abs_min_diff", default=0.6)
    parser.add_argument("--dist_bins", default=16)
    parser.add_argument("--scaling_apol_pol", default=False)
    parser.add_argument("--scaling_all", default=True)
    parser.add_argument("--projection_dims", default=20)
    parser.add_argument("--scheduling", default=True)
    parser.add_argument("--init0iter", default=5)
    parser.add_argument("--backbone", default="egnn")
    parser.add_argument("--extra_edgefeat", default=False)
    parser.add_argument("--randomize", default=0.1)

    # Energy model
    parser.add_argument("--e_lr", default=0.5 * 1.0e-4)
    parser.add_argument("--e_drop_out", default=0.3)
    parser.add_argument("--e_num_layers", default=6)
    parser.add_argument("--e_backbone", default="egnn")
    parser.add_argument("--e_projection_dims", default=20)
    parser.add_argument("--e_l0_in_features", default=1 + 20 + 20 + 1 + 1)
    parser.add_argument("--e_w_loss_vdw", default=1.0)
    parser.add_argument("--e_w_loss_elec", default=1.5)
    parser.add_argument("--e_w_loss_solv", default=1.0)
    parser.add_argument("--e_w_loss_rank", default=1.0)
    parser.add_argument("--e_data_suffix", default="MT_all")

    # Common data params
    parser.add_argument("--subset_size", default=4)
    parser.add_argument("--edge_mode", default="dist")
    parser.add_argument("--ball_radius", default=9)
    parser.add_argument("--edge_dist", default=(8.0, 4.5, 3.0))

    args = parser.parse_args()
    return args


def set_arguments_train():
    parser = argparse.ArgumentParser()
    parser.add_argument("-i", "--input_features")
    parser.add_argument("--model-name", default="test_train")
    parser.add_argument("--data-path")
    parser.add_argument("--AF", help="Path for pLDDT")
    parser.add_argument("--energy-path")
    parser.add_argument("--self-docking", action="store_true")
    parser.add_argument("--no-gald", action="store_true")

    # Local model
    parser.add_argument("--lr", default=6 * 1.0e-4)
    parser.add_argument("--l0_in_features", default=1 + 20 + 20 + 1 + 1)
    parser.add_argument("--num_layers", default=(4, 6, 3))
    parser.add_argument("--inter_hidden_channels", default=(16, 16))
    parser.add_argument("--data_suffix", default=".auxil")
    parser.add_argument("--drop_out", default=0.3)
    parser.add_argument("--use_l1_feature", default=False)
    parser.add_argument("--w_lossG", default=5.0)
    parser.add_argument("--w_lossL", default=0.5)
    parser.add_argument("--w_lossR", default=0.3)
    parser.add_argument("--w_lossHbond", default=1.0)
    parser.add_argument("--w_lossPolApol", default=3.8)
    parser.add_argument("--w_lossApolApol", default=0.8)
    parser.add_argument("--w_lossDist", default=0.05)
    parser.add_argument("--w_reg", default=5.0e-5)
    parser.add_argument("--masking_coeff", default=0)
    parser.add_argument("--fix_random_seed", default=True)
    parser.add_argument("--distance_map_dist", default=5)
    parser.add_argument("--threshold_distance_diff", default=5)
    parser.add_argument("--abs_min_diff", default=0.6)
    parser.add_argument("--dist_bins", default=16)
    parser.add_argument("--scaling_apol_pol", default=False)
    parser.add_argument("--scaling_all", default=True)
    parser.add_argument("--projection_dims", default=20)
    parser.add_argument("--scheduling", default=True)
    parser.add_argument("--init0iter", default=5)
    parser.add_argument("--backbone", default="egnn")
    parser.add_argument("--extra_edgefeat", default=False)
    parser.add_argument("--randomize", default=0.1)

    # Energy model
    parser.add_argument("--e_lr", default=0.5 * 1.0e-4)
    parser.add_argument("--e_drop_out", default=0.5 * 1.0e-4)
    parser.add_argument("--e_num_layers", default=6)
    parser.add_argument("--e_backbone", default="egnn")
    parser.add_argument("--e_projection_dims", default=20)
    parser.add_argument("--e_l0_in_features", default=1 + 20 + 20 + 1 + 1)
    parser.add_argument("--e_w_loss_vdw", default=1.0)
    parser.add_argument("--e_w_loss_elec", default=1.5)
    parser.add_argument("--e_w_loss_solv", default=1.0)
    parser.add_argument("--e_w_loss_rank", default=1.0)
    parser.add_argument("--e_data_suffix", default="MT_all")

    # Common data params
    parser.add_argument("--subset_size", default=4)
    parser.add_argument("--edge_mode", default="dist")
    parser.add_argument("--ball_radius", default=9)
    parser.add_argument("--edge_dist", default=(8.0, 4.5, 3.0))

    args = parser.parse_args()
    return args
